### PR TITLE
Use condition to wait response

### PR DESCRIPTION
**Pull request by norihiro**
### Description

Previously, response is polled `call_poll_delay/2` after sending a message by `call` method. It results each `call` method takes 50 ms at the default parameter. This commit uses a condition object to be notified just after the response was arrived and processed.

With this change, the parameter `call_poll_delay` can be deprecated.

### Motivation
To reduce runtime of `call` method.

### How has This Been Tested?
OS: Fedora release 34
- Checked runtime of `call` becomes faster
  Run a code below and measure the runtime.
  ```
    await ws.connect()
    n = 100
    while n > 0:
        result = await ws.call('GetVersion') # We get the current OBS version. More request data is not required
        # print(result) # Print the raw json output of the GetVersion request
        n -= 1
    await ws.disconnect()
  ```
  Before: 0m5.205s
  After: 0m0.076s
- Checked timeout is processed
  Run a code below and checked timeout message appears after 3 seconds.
  ```
    await ws.connect()
    result = await ws.call('GetVersion', timeout=1)
    print(result)
    result = await ws.call('Sleep', {'sleepMillis': 5000}, timeout=3)
    await ws.disconnect()
  ```

### Types of changes
- Performance enhancement (non-breaking change which improves efficiency)

### CODE REVIEW

**Comment by tt2468** [comment]
Love the idea of using condition variables. I think that we can do it more elegantly though. If I'm understanding correctly, this implementation makes requests run synchronously, essentially removing functionality from the library.

Instead of polling manually with a task, let's do:
- Call `notify_all()` from the `_ws_recv_task` since `notify()` only notifies one waiting task, which I could see causing deadlocks without the polling task
- Use the `asyncio.Condition.wait_for()` call with a callback or lambda which does the normal `if request_id in self.answers` thing
- Use [`asyncio.wait_for()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for) (different call, same name) to perform the request timeout functionality

I should also note that the `simpleobsws-4.x` branch is for obs-websocket 4.x, and the branch for the new 5.x versions is `master`. Perhaps we just merge this PR in its current form and make the suggested improvements to `master`? I'm happy to do them myself unless you are interested.

**Comment by norihiro** [comment]
Modified the code as below.
- Use `notify_all()` instead of `notify()`
- Use `wait_for` to check if the request is ready or timeout happened. Thanks to `wait_for`, a `while` loop is omitted.
- In addition, `_TimeoutNotifier` class is newly introduced to handle the timeout without continuously notify as my previous PR.

**Comment by tt2468** [comment]
Looks great! Thanks for the addition.

**Comment by norihiro** [comment]
> Perhaps we just merge this PR in its current form and make the suggested improvements to master? I'm happy to do them myself unless you are interested.

Comparing 4.x and 5.x, the code looks not much different so that this idea should be applicable to 5.x. However, I have not installed obs-websocket 5.0 yet and I cannot test it. I'm happy if you can implement it to 5.x branch.

**Comment by tt2468** [comment]
Sounds good, I'll implement it on `master` within the next few days.

**Pull request merged**
